### ISSUE TITLE
How do I run this for myself?

### ISSUE THREAD

**Issue by driftywinds** [NickAwrist/Dailycheckin_Bot#4]
I don't see instructions to run this for myself, is that possible?

**Comment by driftywinds** [comment]
Could you provide an example .env file? The container doesn't work without it

**Comment by NickAwrist** [comment]
Here is an example .env file
```
TOKEN=BOT_TOKEN_GOES_HERE
CLIENT_ID=BOT_CLIENT_ID_GOES_HERE
BOT_ADMIN_ID=YOUR_DISCORD_ID_GOES_HERE
```

**Comment by driftywinds** [comment]
Thank you so much, helped alot!
